### PR TITLE
Full cover for lulu.com

### PR DESCRIPTION
**Pull request by Bystroushaak**
I've added full cover for lulu.com with backside.

* http://kitakitsune.org/sync/ebooks/rationality/

### CODE REVIEW

**Comment by jrincayc** [comment]
Thank you.   I was wondering if there was any reason to keep the layers:
* Vložená vrstva
* Vložená vrstva # 4
* Pozadí
in the xcf file since they increase the file size and don't seem to be used in the final version.  Other than that it looks ready to merge.

**Comment by jrincayc** [comment]
The other issue is that you copied the text on the back cover from: https://intelligence.org/rationality-ai-zombies/  Did you get permission to do that, or is there somewhere that says that is permitted?  Thanks.

**Comment by Bystroushaak** [comment]
Good points. The layers are artefacts used when I was creating the file. `Vložená vrstva # 4` is used to slightly darken the semi-transparent layer of the backside, but can be joined.

I will close this pull request and create new one with smaller file without unnecessary layers and I will also rename them to english descriptive titles.

I will also ask for permission to use text on the back cover.

**Comment by jrincayc** [comment]
Okay.  Thanks.  I am guessing Rob Bensinger might be the best person to contact about permissions: https://intelligence.org/team/

**Comment by jrincayc** [comment]
Hm, well, then we may just need to write our back cover blurb.  I wrote a start of one on the wiki: https://github.com/jrincayc/rationality-ai-zombies/wiki/back-cover-blurb   Feel free to add to it, modify it, or completely replace it if you want.

**Pull request closed without merging**
